jobs:
- job: OpenEmbedded_Build_And_Export
  container: smartracks-build
  timeoutInMinutes: 3600
  workspace:
     clean: all
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
      
  steps:
  - checkout: rcu-service
  - checkout: meta-smartracks
  - checkout: smartracks-manifest
  - script: |
      cd $(Build.SourcesDirectory)/smartracks-manifest
      git branch
      git checkout -b main
      repo init -u $(Build.SourcesDirectory)/smartracks-manifest -b main -m smartracks-manifest.xml
      
      mkdir .repo/local_manifests
      cat > .repo/local_manifests/remove-meta-smartracks.xml <<EOF
      <?xml version="1.0" encoding="UTF-8"?>
      <manifest>
        <remove-project name="meta-smartracks.git" />
      </manifest>
      EOF
      
      #git clean -ffdx
      #git reset --hard HEAD
      repo sync --force-sync
      cp  -r $(Build.SourcesDirectory)/meta-smartracks $(Build.SourcesDirectory)/smartracks-manifest/layers
      cp  $(Build.SourcesDirectory)/meta-smartracks/buildconf/export $(Build.SourcesDirectory)/smartracks-manifest
      sed -i 's|S = "${WORKDIR}/git"|#S = "${WORKDIR}/git"|g' $(Build.SourcesDirectory)/smartracks-manifest/layers/meta-smartracks/recipes-core/rcu-service/rcu-service_*.bb
      #sed -i 's|S = "${WORKDIR}/git"|#S = "${WORKDIR}/git"|g' $(Build.SourcesDirectory)/smartracks-manifest/layers/meta-smartracks/recipes-core/rcu-service/rcu-service_1.0.bb
      . export
      echo "INHERIT += \"externalsrc\"" >> $(Build.SourcesDirectory)/smartracks-manifest/build/conf/local.conf
      echo "EXTERNALSRC_pn-rcu-service = \"$(Build.SourcesDirectory)/rcu-service\"" >> $(Build.SourcesDirectory)/smartracks-manifest/build/conf/local.conf
      #bitbake rcu-service 
      bitbake smartracks-minimal-image
      bitbake package-index
      
      cd deploy/images/apalis-imx8x-smartracks
      mkdir build-$(Build.BuildNumber)
      #cp deploy/images/apalis-imx8x-smartracks/$(find . -name 'Apalis-iMX8X-SmartRacks_Reference-Minimal-Image-rt-Tezi_*.tar') build-$(Build.BuildNumber)
      cp $(find -name 'Apalis-iMX8X-SmartRacks_Reference-Minimal-Image-rt-Tezi_*.tar') build-$(Build.BuildNumber)
      cp -R build-$(Build.BuildNumber) /mnt/nirvana/perforceExports/smartracks/development
      
      # go back to deploy directory
      # create feedversion.txt in feed-$(Build.BuildNumber) to clarify feed version
      cd ../..
      mkdir feed-$(Build.BuildNumber)
      echo $(Build.BuildNumber) > feed-$(Build.BuildNumber)/feedversion.txt
      
      # copy all files in deploy/ipk to feed-$(Build.BuildNumber)
      # copy feed-$(Build.BuildNumber) to perforce
      cp -R ipk/* feed-$(Build.BuildNumber)
      cp -R feed-$(Build.BuildNumber) /mnt/nirvana/perforceExports/smartracks/development
      
      # delete latestfeed, then repopulate latestfeed with latest ipk exports
      # this means opkg.conf points to nirvana/perforceExports/smartracks/development/latestfeed/aarch64, etc
      rm -rf /mnt/nirvana/perforceExports/smartracks/development/latestfeed
      mkdir /mnt/nirvana/perforceExports/smartracks/development/latestfeed
      cp -R /mnt/nirvana/perforceExports/smartracks/development/feed-$(Build.BuildNumber)/* /mnt/nirvana/perforceExports/smartracks/development/latestfeed
      
      bitbake smartracks-minimal-image -c populate_sdk
      
      mkdir sdk-$(Build.BuildNumber)
      cp sdk/* sdk-$(Build.BuildNumber)
      cp -R sdk-$(Build.BuildNumber) /mnt/nirvana/perforceExports/smartracks/development
